-- MySQL Script generated by MySQL Workbench
-- Sáb 25 Mar 2017 15:06:59 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melhoridade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema melhoridade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `melhoridade` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `melhoridade` ;

-- -----------------------------------------------------
-- Table `melhoridade`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhoridade`.`status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhoridade`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhoridade`.`tipo` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhoridade`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhoridade`.`data` (
  `id_data` INT NOT NULL AUTO_INCREMENT,
  `criacao` DATETIME NOT NULL,
  `atualizacao` DATETIME NULL,
  PRIMARY KEY (`id_data`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhoridade`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhoridade`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `tipo_id_tipo` INT NOT NULL,
  `status_id_status` INT NOT NULL,
  `data_id_data` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_status1_idx` (`status_id_status` ASC),
  INDEX `fk_usuario_tipo1_idx` (`tipo_id_tipo` ASC),
  INDEX `fk_usuario_data1_idx` (`data_id_data` ASC),
  CONSTRAINT `fk_usuario_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `melhoridade`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_tipo1`
    FOREIGN KEY (`tipo_id_tipo`)
    REFERENCES `melhoridade`.`tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_data1`
    FOREIGN KEY (`data_id_data`)
    REFERENCES `melhoridade`.`data` (`id_data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhoridade`.`idoso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhoridade`.`idoso` (
  `id_idoso` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(150) NOT NULL,
  `tipo_logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `baiiro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(70) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_idoso`),
  INDEX `fk_idoso_usuario_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_idoso_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `melhoridade`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhoridade`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhoridade`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `ddd` INT(2) NOT NULL,
  `telefone` INT(9) NOT NULL,
  `hash` VARCHAR(40) NOT NULL,
  `senha` VARCHAR(40) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionario_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `melhoridade`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhoridade`.`imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhoridade`.`imagem` (
  `id_imagem` INT NOT NULL AUTO_INCREMENT,
  `diretorio` VARCHAR(150) NOT NULL,
  `tipo_id_tipo` INT NOT NULL,
  `status_id_status` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `data_id_data` INT NOT NULL,
  PRIMARY KEY (`id_imagem`),
  INDEX `fk_imagem_status1_idx` (`status_id_status` ASC),
  INDEX `fk_imagem_tipo1_idx` (`tipo_id_tipo` ASC),
  INDEX `fk_imagem_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_imagem_data1_idx` (`data_id_data` ASC),
  CONSTRAINT `fk_imagem_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `melhoridade`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imagem_tipo1`
    FOREIGN KEY (`tipo_id_tipo`)
    REFERENCES `melhoridade`.`tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imagem_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `melhoridade`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imagem_data1`
    FOREIGN KEY (`data_id_data`)
    REFERENCES `melhoridade`.`data` (`id_data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhoridade`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhoridade`.`noticia` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `descricao` TEXT NOT NULL,
  `status_id_status` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `data_id_data` INT NOT NULL,
  PRIMARY KEY (`id_noticia`),
  INDEX `fk_noticia_status1_idx` (`status_id_status` ASC),
  INDEX `fk_noticia_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_noticia_data1_idx` (`data_id_data` ASC),
  CONSTRAINT `fk_noticia_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `melhoridade`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noticia_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `melhoridade`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noticia_data1`
    FOREIGN KEY (`data_id_data`)
    REFERENCES `melhoridade`.`data` (`id_data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhoridade`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhoridade`.`contato` (
  `id_contato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `status_id_status` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `data_id_data` INT NOT NULL,
  PRIMARY KEY (`id_contato`),
  INDEX `fk_contato_status1_idx` (`status_id_status` ASC),
  INDEX `fk_contato_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_contato_data1_idx` (`data_id_data` ASC),
  CONSTRAINT `fk_contato_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `melhoridade`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contato_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `melhoridade`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contato_data1`
    FOREIGN KEY (`data_id_data`)
    REFERENCES `melhoridade`.`data` (`id_data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhoridade`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhoridade`.`menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_menu`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
